Fix bug finding widgets when app name is not "testapp".
When trying out gizmo for the first time the app failed due to:

    java.util.concurrent.ExecutionException: java.lang.Exception:
    Can't resolve widget {:tag :widget, :attrs {:rel
    "testapp.widgets.shared/header"}, :content
    []}. testapp.widgets.shared/header is not found